// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	// The canonical origin for absolute URLs, the sitemap and social cards.
	// Change this if you host the docs somewhere other than GitHub Pages.
	site: 'https://anomalysh.github.io/rift',

	integrations: [
		starlight({
			title: 'rift',
			description:
				'Self-hosted, ngrok-style HTTP tunnels: expose a local port on a public HTTPS URL under a domain you own.',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/anomalysh/rift' },
			],
			// Explicit, ordered sidebar. Not autogenerated: the reading order is
			// deliberate, from installing through to operating a deployment.
			sidebar: [
				{
					label: 'Getting started',
					items: [
						{ label: 'Installation', slug: 'getting-started/installation' },
						{ label: 'Quickstart', slug: 'getting-started/quickstart' },
						{ label: 'Configuration', slug: 'getting-started/configuration' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'TLS modes', slug: 'guides/tls-modes' },
						{ label: 'DNS-01 providers', slug: 'guides/dns-providers' },
						{ label: 'Deploying to a server', slug: 'guides/deploying' },
						{ label: 'Reserved subdomains & tokens', slug: 'guides/subdomains-and-tokens' },
						{ label: 'Multi-node with Redis', slug: 'guides/multi-node' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'CLI', slug: 'reference/cli' },
						{ label: 'Server configuration', slug: 'reference/server-config' },
						{ label: 'Admin API', slug: 'reference/admin-api' },
						{ label: 'Wire protocol', slug: 'reference/protocol' },
					],
				},
				{
					label: 'Architecture',
					items: [
						{ label: 'How it works', slug: 'architecture/how-it-works' },
						{ label: 'Design notes', slug: 'architecture/design-notes' },
					],
				},
				{
					label: 'Operations',
					items: [
						{ label: 'Troubleshooting', slug: 'operations/troubleshooting' },
					],
				},
			],
		}),
	],
});
