# fish completion for rift.
#   Generated by `rift completions fish` from cli/src/cli-spec.ts;
#   do not edit by hand. Regenerate with `make gen-docs`.
#
#   Install into a fish completions dir, e.g.
#   ~/.config/fish/completions/rift.fish

# rift takes a protocol, port, and subdomain: no files.
complete -c rift -f

complete -c rift -l token -r -d 'gateway auth token'
complete -c rift -l server -r -d 'gateway ws/wss URL'
complete -c rift -l host -r -d 'local host to forward to'
complete -c rift -l log-level -x -a 'debug info warn error silent' -d 'log verbosity'
complete -c rift -l insecure -d 'skip TLS certificate verification (wss only)'
complete -c rift -l set-token -r -d 'persist token to the config file and exit'
complete -c rift -l set-server -r -d 'persist server to the config file and exit'
complete -c rift -l set-host -r -d 'persist host to the config file and exit'
complete -c rift -l set-log-level -x -a 'debug info warn error silent' -d 'persist log level to the config file and exit'
complete -c rift -s v -l version -d 'print version and exit'
complete -c rift -s h -l help -d 'print this help and exit'

# First positional is the protocol.
complete -c rift -n 'test (count (commandline -opc)) -eq 1' -a 'http' -d 'forward HTTP requests; the gateway routes by subdomain and terminates TLS'
complete -c rift -n 'test (count (commandline -opc)) -eq 1' -a 'tcp' -d 'forward a raw TCP stream to the local port'
complete -c rift -n 'test (count (commandline -opc)) -eq 1' -a 'tls' -d 'forward a TLS stream, routed by SNI, to the local port'
