#compdef rift
# zsh completion for rift.
#   Generated by `rift completions zsh` from cli/src/cli-spec.ts;
#   do not edit by hand. Regenerate with `make gen-docs`.
#
#   Install as _rift somewhere on $fpath, e.g.
#   /usr/share/zsh/site-functions/_rift
_rift() {
    _arguments -s -S \
        '(- *)'{-v,--version}'[print version and exit]' \
        '(- *)'{-h,--help}'[print this help and exit]' \
        '--token[gateway auth token]:token:' \
        '--server[gateway ws/wss URL]:url:' \
        '--host[local host to forward to]:host:_hosts' \
        '--log-level[log verbosity]:level:(debug info warn error silent)' \
        '--insecure[skip TLS certificate verification (wss only)]' \
        '--set-token[persist token to the config file and exit]:token:' \
        '--set-server[persist server to the config file and exit]:url:' \
        '--set-host[persist host to the config file and exit]:host:_hosts' \
        '--set-log-level[persist log level to the config file and exit]:level:(debug info warn error silent)' \
        '1:protocol:(http tcp tls)' \
        '2:port:' \
        '3:subdomain:' \
        && return 0
}

_rift "$@"
